
[PlankDrawingTheme]
#The roundness of the top corners.
TopRoundness=7
#The roundness of the bottom corners.
BottomRoundness=0
#The thickness (in pixels) of lines drawn.
LineWidth=1
#The color (RGBA) of the outer stroke.
OuterStrokeColor=0;;0;;0;;255
#The color (RGBA) of the inner stroke.
InnerStrokeColor=60;;60;;60;;255
#The starting color (RGBA) of the fill gradient.
FillStartColor=40;;40;;40;;255
#The ending color (RGBA) of the fill gradient.
FillEndColor=8;;8;;8;;255